server:
  port: 8081

spring:
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/board?serverTimezone=Asia/Seoul"
    username: "root"
    password: "0000"

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  mvc:
    path match:
      matching-strategy: ant_path_matcher

  thymeleaf:
    cache : false


path:
  rootMyCom:
    window: "C:\\Temp\\upload\\board\\"
    linux: "/home/ubuntu/upload/board/"
    mac: "??"